title: Technical Council, IIT Gandhinagar


markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_text: "© BidhanIITGN"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Clubs"
   link: "clubs" 
 - name: "Team"
   link: "team"
 - name: "Past Council Members"
   link: "past"
 - name: "Event/Workshops"
   link: "event"
 
